{"level":"error","message":"login failed login failed","stack":"Error: login failed\n    at Object.login (C:\\Users\\mohamad\\Desktop\\auth-project\\src\\routes\\auth\\controller.js:34:11)\n    at newFn (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Object.validate (C:\\Users\\mohamad\\Desktop\\auth-project\\src\\routes\\controller.js:30:5)\n    at newFn (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at middleware (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express-validator\\src\\middlewares\\check.js:16:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"}
{"level":"error","message":"something failed outside something failed outside","stack":"Error: something failed outside\n    at Object.<anonymous> (C:\\Users\\mohamad\\Desktop\\auth-project\\index.js:27:7)\n    at Module._compile (internal/modules/cjs/loader.js:1063:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)\n    at Module.load (internal/modules/cjs/loader.js:928:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:769:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"something failed outside something failed outside","stack":"Error: something failed outside\n    at Object.<anonymous> (C:\\Users\\mohamad\\Desktop\\auth-project\\index.js:31:7)\n    at Module._compile (internal/modules/cjs/loader.js:1063:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)\n    at Module.load (internal/modules/cjs/loader.js:928:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:769:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"something failed outside something failed outside","stack":"Error: something failed outside\n    at Object.<anonymous> (C:\\Users\\mohamad\\Desktop\\auth-project\\index.js:37:7)\n    at Module._compile (internal/modules/cjs/loader.js:1063:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)\n    at Module.load (internal/modules/cjs/loader.js:928:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:769:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"something failed outside something failed outside","stack":"Error: something failed outside\n    at Object.<anonymous> (C:\\Users\\mohamad\\Desktop\\auth-project\\index.js:37:7)\n    at Module._compile (internal/modules/cjs/loader.js:1063:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)\n    at Module.load (internal/modules/cjs/loader.js:928:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:769:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"something failed outside promise something failed outside promise","stack":"Error: something failed outside promise\n    at Object.<anonymous> (C:\\Users\\mohamad\\Desktop\\auth-project\\index.js:33:26)\n    at Module._compile (internal/modules/cjs/loader.js:1063:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)\n    at Module.load (internal/modules/cjs/loader.js:928:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:769:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)\n    at internal/main/run_main_module.js:17:47"}
{"level":"error","message":"login failed login failed","stack":"Error: login failed\n    at Object.login (C:\\Users\\mohamad\\Desktop\\auth-project\\src\\routes\\auth\\controller.js:34:11)\n    at Layer.handle [as handle_request] (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Object.validate (C:\\Users\\mohamad\\Desktop\\auth-project\\src\\routes\\controller.js:30:5)\n    at Layer.handle [as handle_request] (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at middleware (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express-validator\\src\\middlewares\\check.js:16:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"}
{"level":"error","message":"login failed login failed","stack":"Error: login failed\n    at Object.login (C:\\Users\\mohamad\\Desktop\\auth-project\\src\\routes\\auth\\controller.js:34:11)\n    at Layer.handle [as handle_request] (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Object.validate (C:\\Users\\mohamad\\Desktop\\auth-project\\src\\routes\\controller.js:30:5)\n    at Layer.handle [as handle_request] (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at middleware (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express-validator\\src\\middlewares\\check.js:16:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"}
{"level":"error","message":"login failed login failed","stack":"Error: login failed\n    at Object.login (C:\\Users\\mohamad\\Desktop\\auth-project\\src\\routes\\auth\\controller.js:34:11)\n    at Layer.handle [as handle_request] (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Object.validate (C:\\Users\\mohamad\\Desktop\\auth-project\\src\\routes\\controller.js:30:5)\n    at Layer.handle [as handle_request] (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at middleware (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express-validator\\src\\middlewares\\check.js:16:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"}
{"level":"error","message":"login failed login failed","stack":"Error: login failed\n    at Object.login (C:\\Users\\mohamad\\Desktop\\auth-project\\src\\routes\\auth\\controller.js:34:11)\n    at Layer.handle [as handle_request] (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Object.validate (C:\\Users\\mohamad\\Desktop\\auth-project\\src\\routes\\controller.js:30:5)\n    at Layer.handle [as handle_request] (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at middleware (C:\\Users\\mohamad\\Desktop\\auth-project\\node_modules\\express-validator\\src\\middlewares\\check.js:16:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)"}
